# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitoring.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'monitoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10monitoring.proto\x12\nmonitoring\"n\n\x0c\x41gentMetrics\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x11\n\tcpu_usage\x18\x03 \x01(\x01\x12\x11\n\tram_usage\x18\x04 \x01(\x01\x12\x12\n\ndisk_usage\x18\x05 \x01(\x01\"-\n\nMetricsAck\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2V\n\x11MonitoringService\x12\x41\n\rSubmitMetrics\x12\x18.monitoring.AgentMetrics\x1a\x16.monitoring.MetricsAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTMETRICS']._serialized_start=32
  _globals['_AGENTMETRICS']._serialized_end=142
  _globals['_METRICSACK']._serialized_start=144
  _globals['_METRICSACK']._serialized_end=189
  _globals['_MONITORINGSERVICE']._serialized_start=191
  _globals['_MONITORINGSERVICE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
